openapi: 3.1.0
info:
  title: "API de consutório"
  version: 0.0.1
  description: "API para controlar médicos e suas especialidades dentro do consultório."
  termsOfService: https://mockapi.io
  contact:
    name: "Suporte a Devs"
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licences/gpl-3.0.html
externalDocs:
  description: "Documentação burocrática."
  url: https://mockapi.io
servers:
- url: https://6515b69909e3260018c90c72.mockapi.io/
  description: "Api de Homologação"
- url: https://6515b69909e3260018c90c72.mockapi.io/
  description: "Api de Produção"
paths: 
  /especialidades:
      get:
        summary: "Recupera todas as especialidades."
        responses:
            200:
              description: "Sucesso."
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        descricao:
                          type: string
      post:
        summary: "Cria uma nova especialidade."
        description: "Através desse endepoint, é possivel criar novas especialidades."
        requestBody: 
          content:
            application/json: 
              schema:
                type: object
                properties:
                  descricao:
                    type: string
        responses:
          201:
            description: "Sucesso."
            content:
              application/json: 
                schema:
                  type: object
                  properties:
                    descricao:
                      type: string
  /especialidades/{id}:
    parameters:
      - name: id
        required: true
        in: path
        schema:
          type: integer
    get:
      summary: "Recupera uma entidade pelo ID."
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: integer
      responses:
        200:
          description: "Sucesso."
          content:
            application/json: 
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                    type: string
        404:
          description: "Especialidade não encontrada."
          content: 
            application/json: 
              example: "Not Found"